name: Matrix
on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log node version
        run: node -v
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Log node version
        run: node -v
